# Generated by Django 5.1 on 2024-08-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('bio', models.TextField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('linkdin', models.EmailField(max_length=200, null=True)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
    ]
